### ISSUE TITLE
Enable to Run the Code

### ISSUE THREAD

**Issue by hamzaaslam0497** [iam-mhaseeb/Instagram-Bot#1]
I have installed dependencies (selenium and pandas) and pasted code in pycham, but still not be able to run the code.
Following errors are coming.

"C:\Users\Hamza Aslam\AppData\Local\Programs\Python\Python37-32\python.exe" "C:/Users/Hamza Aslam/PycharmProjects/insta/instabot.py"
Traceback (most recent call last):
  File "C:\Users\Hamza Aslam\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\Users\Hamza Aslam\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Hamza Aslam\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Hamza Aslam/PycharmProjects/insta/instabot.py", line 9, in <module>
    webdriver = webdriver.Chrome(executable_path=chromedriver_path)
  File "C:\Users\Hamza Aslam\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\Hamza Aslam\AppData\Local\Programs\Python\Python37-32\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by iam-mhaseeb** [comment]
Your path for selenium driver is not right. See these links for more details:
https://stackoverflow.com/questions/49153985/unable-to-add-selenium-library-in-pycharm
https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000255250-Selenium-ChromeDriver-path-issue-with-PyCharm
